model_type: autoencoder
sample_size: 65536
sample_rate: 44100
audio_channels: 2
model:
    latent_dim: 128
    downsampling_ratio: 512
    io_channels: ${audio_channels}
    encoder:
        type: oobleck
        config:
            in_channels: ${audio_channels}
            channels: 128
            c_mults: [1, 2, 4, 8, 16]
            strides: [2, 2, 4, 4, 8]
            latent_dim: ${model.latent_dim}
            use_snake: true
    decoder:
        type: oobleck
        config:
            out_channels: ${audio_channels}
            channels: 128
            c_mults: [1, 2, 4, 8, 16]
            strides: [2, 2, 4, 4, 8]
            latent_dim: ${model.latent_dim}
            use_snake: true
            final_tanh: false
    bottleneck:
        type: ae
training:
    learning_rate: 1e-4
    warmup_steps: 0
    use_ema: true
    optimizer_configs:
        autoencoder:
            optimizer:
                type: AdamW
                config:
                    betas: [0.8, 0.99]
                    lr: 1.5e-4
                    weight_decay: 1e-3
            scheduler:
                type: InverseLR
                config:
                    inv_gamma: 200000
                    power: 0.5
                    warmup: 0.999
        discriminator:
            optimizer:
                type: AdamW
                config:
                    betas: [0.8, 0.99]
                    lr: 3e-4
                    weight_decay: 1e-3
            scheduler:
                type: InverseLR
                config:
                    inv_gamma: 200000
                    power: 0.5
                    warmup: 0.999
    loss_configs:
        discriminator:
            type: encodec
            config:
                filters: 64
                n_ffts: [2048, 1024, 512, 256, 128]
                hop_lengths: [512, 256, 128, 64, 32]
                win_lengths: [2048, 1024, 512, 256, 128]
            weights:
                adversarial: 0.1
                feature_matching: 5.0
        spectral:
            type: mrstft
            config:
                fft_sizes: [2048, 1024, 512, 256, 128, 64, 32]
                hop_sizes: [512, 256, 128, 64, 32, 16, 8]
                win_lengths: [2048, 1024, 512, 256, 128, 64, 32]
                perceptual_weighting: true
                scale: mel
                n_bins: [320, 160, 80, 40, 20, 10, 5]
            weights:
                mrstft: 1.0
        time:
            type: l1
            weights:
                l1: 0.0
demo:
    demo_every: 2000
    sample_rate: ${sample_rate}
    sample_size: ${sample_size}