model_type: bsroformer_t
sample_rate: 44100
mono: false

model:
  _target_: mss.models.bs_roformer.bs_roformer_bsunet2_t.BSRoformerUNet
  input_channels: 2
  sr: ${sample_rate}
  mel_bins: 256
  n_fft: 2048
  hop_length: 441 
  channels: 128
  channel_multipliers: [1, 2, 4, 4]
  block_types: [resblock, resblock, resblock+bst, resblock+bst]
  depths: [2, 2, 3, 3]
  n_heads: 8
  tf_layers: 1
  checkpoint: false

training:
  use_ema: true
  optimizer_configs:
    mss:
      optimizer:
        type: AdamW8bit
        config:
          lr: 5e-5
          betas: [0.9, 0.999]
          weight_decay: 1e-3
      scheduler:
        type: CosineDecayLR
        config:
          warmup_steps: 1
          total_steps: 1000000
  
demo:
  sample_rate: ${sample_rate}
  sample_steps: 5
  demo_every: 1

validation:
  validate_every: 1
  root: /datasets/musdb18hq
  splits: [train, test]
  sr: ${sample_rate}
  clip_duration: 2.
  evaluate_num: 10
  source_types: [vocals, drums, bass, other]
  target_source_type: vocals
  batch_size: 16
  sample_steps: 5