---
audio_channels: &audio_channels 2
sample_rate: &sample_rate 48000
load_duration: 4.
segment_duration: 3.
target_stem: "vocals"

augmentation:
    cpu:
        mixing:
            intra_source:
                min_sources: 1
                max_sources: 3

            extra_source:
                time_align: "random"  # "strict" | "group" | "random"

        gain:
            enabled: true
            min_db: -6.0
            max_db: 6.0

        eq:
            enabled: true
            min_db: -6.0
            max_db: 6.0
            n_bands: 8

        resample:
            enabled: true
            min_ratio: 0.95
            max_ratio: 1.05


train_datasets:
    MUSDB18HQIntraMix:
        root: "/datasets/musdb18hq"
        split: "train"

test_datasets:
    MUSDB18HQ:
        root: "/datasets/musdb18hq"
        split: "test"

sampler: RandomSongSamplerMix

model:
    name: BSRoformer68
    audio_channels: *audio_channels
    sample_rate: *sample_rate
    n_fft: 2048
    hop_length: 480
    n_bands: 64
    dim: 384
    dim_sp: 96
    dim_head: 32
    patch_size: [4, 4]
    n_layers: 6
    n_pre_layers: 1
    n_post_layers: 1
    pre_time_block: True
    post_time_block: True
    use_checkpoint: True
    delta_attn_ratio: 2
    conv_kernel_size: 7

train:
    device: cuda
    num_workers: 8
    # num_workers: 0
    precision: "bf16"  # "no" (fp32) | bf16"
    loss: l1_wav_l1_multistft
    optimizer: AdamW
    lr: 3e-4
    max_grad_norm: 1.0 # Leave blank if no gradient clipping is used
    warm_up_steps: 1000  # Leave blank if no warm up is used
    batch_size_per_device: 4
    gradient_accumulation_steps: 1
    test_every_n_steps: 20000
    save_every_n_steps: 50000
    training_steps: 1000000
    resume_ckpt_path:  # Leave blank if train from scratch

validate:
    audios_num: 5
