model_type: diffusion_mss
sample_rate: 44100
audio_channels: 2

model:
  io_channels: 64
  mixture_dim: 64
  mixture_max_seq_len: 64
  pretransform:
    type: diffusers_autoencoder
    config:
      path: pretrained/stable-audio-vae
  diffusion:
    input_concat_ids: [mixture]
    type: dit
    diffusion_objective: rectified_flow
    config:
      io_channels: 64
      embed_dim: 1024
      input_concat_dim: 64
      depth: 16
      num_heads: 16
      transformer_type: continuous_transformer
      attn_kwargs:
        qk_norm: rms

training:
  use_ema: true
  target_instrument: vocals
  optimizer_configs:
    diffusion:
      optimizer:
        type: AdamW
        config:
          lr: 1e-4
          betas: [0.9, 0.999]
          weight_decay: 1e-3
      scheduler:
        type: InverseLR
        config:
          inv_gamma: 1000000
          power: 0.5
          warmup: 0.99

demo:
  sample_rate: ${sample_rate}
  demo_every: 2000
  demo_steps: 50
  demo_cfg_scales: [1, 3, 5, 7, 9]