sample_rate: 44100
mono: false

model:
  _target_: models.bs_roformer.BSRoformer
  n_fft: 2048
  hop_length: 441
  time_stacks: 4
  depth: 12
  dim: 384
  n_heads: 12

training:
  use_ema: true
  optimizer_configs:
    mss:
      optimizer:
        type: AdamW
        config:
          lr: 1.5e-4
          betas: [0.9, 0.999]
          weight_decay: 1e-3
      scheduler:
        type: InverseLR
        config:
          inv_gamma: 1000000
          power: 0.5
          warmup: 0.99
  loss_configs:
    spectral:
      type: mrstft
      config:
        fft_sizes: [4096, 2048, 2048, 2048, 2048]
        hop_sizes: [147, 147, 147, 147, 147]
        win_lengths: [4096, 2048, 1024, 512, 256]
      weights:
        mrstft: 0.

    time:
      type: l1
      weights:
        l1: 1.
  
demo:
  sample_rate: ${sample_rate}
  demo_every: 2000

validation:
  validate_every: 5000
  root: /datasets/musdb18hq
  splits: [train, test]
  sr: ${sample_rate}
  clip_duration: 2.
  evaluate_num: 10
  source_types: [vocals, drums, bass, other]
  target_source_type: vocals
  batch_size: 8